### ISSUE TITLE
[Improvement] Customize MultiQC report with a FooDMe 2 design.

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#42]

**Comment by marchoeppner** [comment]
After reading the MultiQC documentation, I am not sure we can easily do this. Seems to me that such a new template must be installed and can't simply pointed to: https://multiqc.info/docs/development/templates/

And as long as we want to support containers and conda, adding our own multiqc package seems out of scope..

So for the moment, I suppose we are stuck with the default MultiQC theme.

**Comment by gregdenay** [comment]
Fine by me
