### ISSUE TITLE
[Feature] Database name and version in report

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#43]

**Comment by marchoeppner** [comment]
The database is generally locked to the pipeline version, so there is perhaps no need to emit that separately. But we should probably add the database versions to the documentation. 

The db and primers are not included with pipeline_info/pipeline_report.txt and the BLAST_BLASTN module additionally emits the file name of the database used. 

Would that work? Else we need to put in a little more effort to a) augment the resources.config to hold the relevant information and build some kind of additional process that reads and emits that to feed into MultiQC alongside the default versions channel that holds the module versions. Thoughts?

**Comment by marchoeppner** [comment]
Implemented in commit 8774c674e209abf589668d2772cf7f55787930e2

**Comment by gregdenay** [comment]
This looks perfect :)
