### ISSUE TITLE
[Feature] Add per-sample JSON report

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#54]
We currently only have non-computer-friendly output types (Krona, XLSX, MultiQC). I think it would be nice to also have a JSON for each sample. I am thinking of wiring this into an automatic pipeline to send results into our LIMS, for example. 

- QC Werte
- read count before after trimming
- taxa table
- pipeline version
- databases version

**Comment by gregdenay** [comment]
@marchoeppner could you check the latest commit ?
I implemented the sample-wise JSON report. It is tested for Illumina data with conda so Ithink I didn't break anything but it would be great if you could check it with your ONT data and singularity/docker just to be sure everything works fine.

**Comment by marchoeppner** [comment]
> @marchoeppner could you check the latest commit ? I implemented the sample-wise JSON report. It is tested for Illumina data with conda so Ithink I didn't break anything but it would be great if you could check it with your ONT data and singularity/docker just to be sure everything works fine.

Runs through just fine on my end, good job! The JSON is pretty "dense" (i.e. all the blast hits) - which is maybe a little confusing for some users, but ultimately fine with me. Definitely useful to have the option to keep that information somewhere.

**Comment by marchoeppner** [comment]
Ah, it seems the various files are not correctly joint along the way so you end up with mis-matching reports:

dada_mqc.json  
ERR10436092.filtered.json  
ERR10436094.composition.json  
ERR10436102.consensus.json  
ERR10436102.cutadapt_mqc.json  
software_versions.yml

**Comment by marchoeppner** [comment]
Fixed in 99fd51491c92a08b7f6485fc94191130296c2bd2

See: https://github.com/bio-raum/FooDMe2/blob/99fd51491c92a08b7f6485fc94191130296c2bd2/subworkflows/reporting/main.nf#L42

**Comment by gregdenay** [comment]
so i did break things, I knew it couldn't be that easy. 
Thanks for the fix
