### ISSUE TITLE
[Improvement] Revert Cutadapt module to Foodme1 implementation to properly deal with 5'<->3' trimming

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#56]
Basically, we need cutadapt to only allow reads to pass that are trimmed on both ends if --cutadapt_trim_3p is enabled. Right now, the argument for only allowing trimmed reads to pass doesn't care if only one or both ends are trimmed. This was previously handled by using two consecutive trimming steps, connected by a pipe. 

We had this changed at some point, the original implementation is here:
https://github.com/bio-raum/FooDMe2/blob/ae6a9657edb0f37cc1a9e962725337b881c9bde1/modules/cutadapt/main.nf

Will also need a way to emit and combine JSON reports for MultiQC, however. ^

- Split using pipes and generate custom table for MultiQC or check if directly possible to add in MQC
- Submit issue to cutadapt repo

**Comment by marchoeppner** [comment]
Potential solution committed in #5710471418f7fc99cdaefcb149a511a7794f3078
