### ISSUE TITLE
[Improvement] Doc improvement

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#57]
- Quickstart
 - Links
 - mkdoc format
 - correctness and clarity check
 - structure ?

**Comment by marchoeppner** [comment]
Just as a reminder to us, we should probably remove any mentioning of support for ONT/Pacbio/Torrent for the time being. This will only confuse people.

**Comment by gregdenay** [comment]
I removed mentions of ONT for now.
I polished things a bit and forced the doc deployment from the dev branch.
There is still room for improvements but it looks fine.

Do you see the need for additional changes on the form and/or content?

**Comment by gregdenay** [comment]
Ah and images have to be packed under `docs/img/` otherwise it's a mess to access them from the doc

**Comment by marchoeppner** [comment]
Right, so I am just listing things to make sure I am not accidentally breaking your nice documentation ;) Looks really great now.

- Pacbio/Torrent/ONT still need to be removed from the usage information
- Quickstart - links to "Installation" and "usage" don't work
- Requirements - links to "Installation" do not work
- Usage: links to "installation" do not work
- Validation: Link to "usage" does not work

**Comment by gregdenay** [comment]
Links fixed (for the record they should be relative paths from the current file, NOT from the doc root)
I removed the sequencing technology section of Usage doc

I'll try to implement doc versionning with [mike](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/).

We should update the dag diagram but it already looks kind of crazy. Maybe we could put a fancy subway plan style diagram like in the nf-core pipeline? What do you think?

**Comment by marchoeppner** [comment]
The subway-style diagrams in nf-core are hand-made in Illustrator or something like that - so yes, doable, but ...any volunteers? ;) In any case, not absolutely necessary for the 1.0 target, I suppose.

**Comment by gregdenay** [comment]
https://github.com/bio-raum/FooDMe2/blob/dev/docs/img/pipeline_dag.png

**Comment by marchoeppner** [comment]
Just noticed that the FooDMe paper isn't referenced anyway. Probably something you would want to add? I mean, it is still "FooDMe", so short of us writing this up already as a follow-up or application note, it makes sense to at least cite the original paper.

**Comment by gregdenay** [comment]
Versionning is working. Note that the url must be [bio-raum.github.io/FooDMe2/latest](https://bio-raum.github.io/FooDMe2/latest)

**Comment by marchoeppner** [comment]
Very nice! Any idea why the "latest" version isn't showing the logo?

**Comment by marchoeppner** [comment]
Nevermind, you haven't merged dev into main yet.

**Comment by marchoeppner** [comment]
The troubleshooting link is dead (typo, I am guessing):
https://bio-raum.github.io/FooDMe2/latest/toobleshooting.md

**Comment by gregdenay** [comment]
I switched the doc build to a strict mode so that the github action will should on missing links and documents.
Fixed the links.
Favicon is now displaying correctly (dev doc).

That's all I had on my list. Do you still have changes for the doc?

**Comment by gregdenay** [comment]
Ha nevermind still need to build a redirect from <https://bio-raum.github.io/FooDMe2> to <https://bio-raum.github.io/FooDMe2/latest>, no diea why mike didn't do it

**Comment by marchoeppner** [comment]
Looks good on the dev branch, maybe best to do a pr into main to see if everything transfers ok. And then do a final check of everything (incl. docs) - and if that all looks good, do the 1.0 release.

**Comment by gregdenay** [comment]
It set it up so that the 'latest' doc is only replaced on **release**, that should happen automatically (tested yesterday with 1.0.0.alpha.2).
I'll open a PR
