### ISSUE TITLE
💡 [REQUEST] - Add read count to XLS table

### ISSUE THREAD

**Issue by marchoeppner** [bio-raum/FooDMe2#67]
### Is your feature request related to a problem?

Too lazy to dig up actual read counts to evaluate sample/call quality ;)

### Describe the solution you'd like

We need to extract and add the actual read counts per taxonomic assignment and sample to the Excel table (also recommended in L 00.00-184). The excel table is based on the composition file, which is currently lacking that information - i.e. needs to be added for this to work. 

### Description

See solution.

**Comment by gregdenay** [comment]
I support this.
We should also add the % of assigned reads in addition to % of all reads.

**Comment by marchoeppner** [comment]
Added in commit dcfe7ff

Could you clarify what you were thinking re: % assigned reads?

**Comment by gregdenay** [comment]
The % amount but with the unassigned reads removed from total. 
The rational is that unassigned reads are usually problematic and should be removed as a QC step. This is considering that the DB ist "complete" though.
