### ISSUE TITLE
💡 [REQUEST] - MultiQC 'General Statistics' is useless

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#68]
### Is your feature request related to a problem?

The information contained in the General statistics table is quite useless to evaluate the quality of the results.

### Describe the solution you'd like

Following fields should be present:

- Sample name
- Total reads
- Q30
- Insert size
- % assigned

possibly more, I am open to suggestions. It is probably better to keep it short and to the point though.

### Description

Alternatives are extracting the info from the graphs or digging in the output files.

**Comment by marchoeppner** [comment]
Fair enough!

Most of that comes from FastQC; we can add it as a module after trimming. 

The % assigned is probably "custom"; need to look into how to get custom data in the "general statistics" section.

**Comment by marchoeppner** [comment]
As far as I can tell, some of the desired metrics are not captured by the MultiQC parser. So we would either have to come up with one or several custom mqc reports and get those into the general statistics section, or just leave the MultiQC "as is" and write a completely but to-the-point Jinja2 template and "roll our own" report. 

I am leaning towards the latter, since I have to do that for GABI also. So we could use a common design language across both pipelines anyway.

**Comment by marchoeppner** [comment]
I have added a new HTML report (reports/RUN_NAME.html) as a more focused alternative to MultiQC. Happy to discuss if this is worth investing more time into. 

To test, just run the current dev branch.

**Comment by gregdenay** [comment]
It's a neat solution, that free us from MultiQC. I think we had already noticed some limitaitons before.
We could use something like [quarto](https://quarto.org/) that takes care of all the annoying HTML stuff for us. That would allow us to write the report in a Jupyter notebook-like format as a jinja tempate and publish it with quarto in HTML (+PDF if we want). It has plugins for plotly and interactive tables so this would be covered too. Let me know what you think, I could start to implement the current version in quarto to see how it is (That's what I am using for the bacterial surveillance dashboard).

We could embedded the krona charts instead of redoing it in barcharts (these colors put my logo to shame :eyes:).

In the table at the start I would suggest ot put % of total reads instead of the raw counts, it would be easier to interpret.

**Comment by marchoeppner** [comment]
Sounds good, go ahead. The current report is compiled with bin/foodme2.py und rendered into assets/foodme2_template.html - feel free to take that as a starting point. 

The template is its own channel now, which would allow people to roll their own reports using FooDMe2 by passing their Jinja template as a command line option. Maybe not worth investing any energy on, but it could be a nice "benefit" somewhere down the road (say, if you want to have a report with your own coporate branding on it)

**Comment by marchoeppner** [comment]
re: Quarto. Just as a small "catch", that library does not seem to be available through any (bio)conda package. So getting that into the pipeline might prove a little more complicated. 

Depends also on whether the work required to do it in "real" HTML is all that great. I'd leave that up to you.

**Comment by marchoeppner** [comment]
Singularity will convert docker on-the-fly, so that should be no problem. The little code block inside the module will look a little different, that's (i.e. no "switch for docker vs singularity).

**Comment by gregdenay** [comment]
RE Quarto: I have added a quarto template under assets (.qmd file) and added it to the workflow, it should work from the latest dev commit. Let me know what you think.
It should be easy enough to add the rest of the metrics from the JSON files by adapting the insert size code block.
We can expand on the template by adding a logo and providing a CSS for full customization, if we want to go there.

Could you check if the docker image I provided works and if I provided it correctly for singularity? I packed everything under `helper/html_report` and renamed your version to `backup_html_report` 

The only thing I couldn't do was the nice tooltips.

**Comment by marchoeppner** [comment]
I think you haven't yet committed that change

**Comment by gregdenay** [comment]
Done

**Comment by marchoeppner** [comment]
```
 
  Starting python3 kernel...Traceback (most recent call last):
    File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
      from notebook import notebook_execute, RestartKernel
    File "/opt/quarto/share/jupyter/notebook.py", line 17, in <module>
      import nbformat
  ModuleNotFoundError: No module named 'nbformat'
  Python 3 installation:
    Version: 3.11.2
    Path: /usr/bin/python3
    Jupyter: (None)
 
  Jupyter is not available in this Python installation.
  Install with python3 -m pip install jupyter
```

I am guessing the container is incomplete in some respects. Works ok when using conda though. That's always the danger when using disparate docker and conda setups. Might be necessary to build our own container for this particular use case, using conda internally to make sure the versions are exactly the same  and both environments complete. 

The report as such looks good; maybe worth doing some additional styling on down the road. But totally usable "as is".

**Comment by gregdenay** [comment]
I tried an alternative image, could you gibe it a try?
There are a bunch on Dockerhub, just have to findthe good one :s

**Comment by marchoeppner** [comment]
So even the "Jupyter" flavor of the Quarto lacks Jupyter, which is...well. 

Running `quarto check` yields:

```

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter
```

Seems like that is a problem with the container - I'll try to get feedback from the developers. A more immediate solution, as mentioned, would be to roll our own quarto container.

**Comment by marchoeppner** [comment]
Success - although this was a bit more annoying than expected. I have created a custom docker container mhoeppner/quarto:latest which works. 

For the moment, this is a workable solution.

**Comment by gregdenay** [comment]
Would it be doeable to add the ìtable`plugin to the image (and conda env) then?

That would allow us to use HTML content in the table (thinking tooltips) and color the cells.

**Comment by marchoeppner** [comment]
The container is based on the conda environment of the respective module, minus quarto (which I had to install from the quarto deb repo, because...reasons). 

So if itable is already available through any of the conda packages, the answer is yes. Else, if it is available as a conda package, I can re-build the container with it.

**Comment by marchoeppner** [comment]
you know what, am just gonna rebuild it with itables from conda-forge, just in case ;)

**Comment by gregdenay** [comment]
https://anaconda.org/conda-forge/itables

`itables = 2.2.2`

**Comment by marchoeppner** [comment]
On that note, I have locked quarto to 1.5.57 in the container. I suppose versioning isn't quite as critical for the reporting step, but generally good practice (the current env yaml has no versions specified for any of the packages, which may result in problems somewhere down the road perhaps).

**Comment by gregdenay** [comment]
Could you give me the cconda env file you use for the docker image? So I can pin the same versions in the conda env for the FooDMe module.

**Comment by gregdenay** [comment]
So the report should be pretty much complete now and I improved the design a bit.
Still to do:
- [ ] clean up MultiQC
- [ ] clean up jinja templating
- [ ] pin versions in conda env

**Comment by gregdenay** [comment]
I also added a very basic QC check to the quarto template:
- if either of the `cutadapt` , `clustering` or `composition` section is missing from the sample report, it is flagged as `fail`
- if either less than 80% of total reads or less than 10 000 reads are available for assignement, it is flagged as `warn`
It eemed relatively sound to me but I am open to change it

**Comment by marchoeppner** [comment]
The new report is excellent, glad we switched over from MultiQC (which we can keep for people that have use for it...). 

As for the various QC qualifiers - I think it is useful to have. That said, I am not 100% sure how we can sensibly defined certain thresholds (I am struggling with this anyway as I prepare the various documentation for our QM). "Sensible" is always good, but in the end it needs to have some scientific basis - which i am not 100% sure about. 

Say, if we have enough "total reads" for analysis, based on some (also sort of arbitrary) threshold, the data should be "good to use", no? It seems a little easier to come up with numbers for the bacterial assemblies somehow..

Absolutely "food for thought" and something we can take "offline" for a discussion.

**Comment by gregdenay** [comment]
Glad you like it!

It's true that there is an absolute threshold of reads for usable data, but if a significant part of reads (say 20%) get lost during the analysis, it is supsicious that something didn't go quite right and it should be investigated.

**Comment by marchoeppner** [comment]
True; but then again, it might be primer-set specific - like, certain taxonomic groups could theoretically always have a lower data quality (lower complexity target region or whatever). So then it would make sense to focus more on a normal distribution from all the samples, and highlight outliers. But that requires both enough samples and of course would not help highlighting a completely failed run etc. So a little tricky. 

But I can live with some "crude" thresholds for the moment; maybe we can improve this down the road.
