### ISSUE TITLE
💡 [REQUEST] - Report, hightlight status across fields

### ISSUE THREAD

**Issue by marchoeppner** [bio-raum/FooDMe2#72]
### Is your feature request related to a problem?

Right now the Quarto report flags samples as pass/warn/fail based on somewhat "crude" thresholds. But it does not tell the user which parameter has triggered a warn or fail. 

### Describe the solution you'd like

We should probably curate a json file with parameter-specific thresholds so that the relevant fields in the summary table can then be coloured accordingly. 

### Description

See above.

**Comment by gregdenay** [comment]
What kind of threshold would you set? 
Would it be a parameter set for each primer_set ?

**Comment by marchoeppner** [comment]
I am lacking the expertise "in production" to really make an educated guess here. 

Maybe easiest to come up with something that is independent of additional curation per primer. 

Stuff like::
at least 75% of reads pass trimming
at least 85% of reads@Q30
no more than 10% chimera

Something like that maybe? We can always tweak if when we learn about new primer sets and their specific "peculiarities".

**Comment by gregdenay** [comment]
I use "no more that 10% loss at each step" as a rule of thumb but it's kind of arbitrary.
The Q30 reccomendations actually depend on the sequencing tech/flowcell used. I'm not sure ONT reaches even 70% Q30, and it shouldn't be a problem on long amplicons.

We could also decide to skip warnings and only flag samples that actually fail, until the working groups come up with QC filters.

**Comment by marchoeppner** [comment]
Maybe that (waiting for official recommendations) is the way to go for the moment. Since people can now easily export the entire summary table, they are obviously free to just apply their own QC filters afterwards.

**Comment by gregdenay** [comment]
I disbaled the `warn` flag for now.

We can keep this issue open until there are officail recommendations

**Comment by gregdenay** [comment]
Reimplemented status check:
- FAIL if no composition determined or less than 500 reads after clustering
- WARN if more than 10% read loss during either read filtering or clustering steps

Still pretty basic but should raise some flags and prompt users to go check their data.
We could think about adding a troobleshouting section to the doc in the future
