### ISSUE TITLE
🐛 [BUG] - Report, tabbed results narrower on second and subsequent tabs

### ISSUE THREAD

**Issue by marchoeppner** [bio-raum/FooDMe2#73]
### Description

Not really a bug, just an asthetic nitpick. The tabbed results are narrower on tab 2 and onwards - whereas the plot in the first tab fills the width of the page, the others seem limited to ~500-600px for some reason. Couldn't quite figure out where this is controlled. 

### Nextflow version

24.04.04

### Pipeline version

dev

### Reproduction steps

```bash
Normal pipeline execution.
```

### Deployment

Singularity

### OS

Linux

**Comment by gregdenay** [comment]
It seems to be an old bug in quarto that should hopefully be fixed at some point.
I will make a reprex and bump the issue again.

https://github.com/quarto-dev/quarto-cli/discussions/2082

**Comment by gregdenay** [comment]
Ctrl+scroll (zoom in or out) refreshes the view and fixes the graphs

**Comment by gregdenay** [comment]
Sorry that's the stale discussion, the issue link is here:
https://github.com/quarto-dev/quarto-cli/issues/4705

There seems to be a fix already I will check that

**Comment by gregdenay** [comment]
Fixed in 8ac5fe3
