### ISSUE TITLE
💡 [REQUEST] - Non overlapping reads support

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#77]
### Discussed in https://github.com/bio-raum/FooDMe2/discussions/76

<div type='discussions-op-text'>

<sup>Originally posted by **gregdenay** November 22, 2024</sup>
Hi @marchoeppner 

some colleagues that are actively working on method developement have barcodes that are a bit to long, meaning read merging is not possible. This is in particular true for the published fish barcodes and some of the plants, already while using the 2x250bp chemistry.
Their strategy for now is to run the analysis independently for R1  and R2 and try to manually merge the end results by hand.

I would assume that one could simply merge R1 and R2 after denoising or prior to identity clustering (eventually with a padding sequence in the middle). Since BLAST is a local aligner, opening gaps is not a problem and the successive steps should actually work fine, mybe with some adapted parameters in the blast search.

What do you think?

Implementation-wise it should actually be straigthforward to do it as an experimental feature. VSearch supports this with the `--fastq_join` parameter (instead of `--fastq_merge`) and DADA's `mergePairs` has a `justConcatenate=TRUE` argument. Both insert an `NNN` padding sequence (length 8 for VSearch and 10 for DADA2).
</div>

**Comment by marchoeppner** [comment]
I noticed that the logic for merging vs joining in vsearch is reversed; will push a fix later.

**Comment by marchoeppner** [comment]
As you would expect, I found a bunch of problems with the current pipeline to make this work ;)

Various changes included in a034a52967f0a87a3da072fa1d6a3e3a9d351c09

Bascially, some of the default settings wouldn't allow joint reads to pass through, like the "max_n" filter and others. This has all been adjusted and data is running through now; however, some of the processes still fail - which relates to #70 and will be partly addressed once that change is implemented.

**Comment by gregdenay** [comment]
For DADA2, the max EE and MaxN parameters are used before joining, so it shouldn't be a problem. 
We should consider firltering reads before joining for VSEARCH as well.

**Comment by gregdenay** [comment]
RE maxNs.

I am not too fond of implementing opaque argument overrides for special cases. 
I think the cleanes solution would be to rn the VSEARCH workflow as:
FILTER(maxEE, maxNs) > MERGEPAIRS > FILTERAGAIN(min_length, max_length)

This would:
1. allow to still filter based on quality while incorporating a bunch of Ns between the reads
2. enforce this filtering to be done at the read (not merged pairs) level, like for DADA2

**Comment by marchoeppner** [comment]
I see... yes, I cannot immediately think of another way to achieve this (stupid large amplicons..).

**Comment by gregdenay** [comment]
I Implemented the suggestions above for VSEARCH and rolled back the conditionnal override of maxNs and blast_qcov for non-overlapping reads.

The fungi dataset is actually messed up by the qcov parameter, so need to drastically lower it manually. I will add a mention of this in the doc so users think about it. it actually make sense since the best BLAST hits have about 50% coverage of the query. 
This is now rather a question of whether it is a good idea to sequence these barcodes with only 150bp, but that's up to the users.
