### ISSUE TITLE
🐛 [BUG] - `remove_chimera` is ignored

### ISSUE THREAD

**Issue by gregdenay** [bio-raum/FooDMe2#79]
### Description

The remove_chimera BOOL parameter is only present in the nextflow.config file and has no effect on workflow execution. Chimeras will always be filtered.
Setting this parameter to true should skip chimera filtering.

### Nextflow version

24.04.10

### Pipeline version

1.0.0

### Reproduction steps

```bash
nextflow run main.nf -profile test,conda
```

### Deployment

Conda/Mamba

### OS

Linux

**Comment by marchoeppner** [comment]
Implemented for vsearch in ce8dd1d

**Comment by gregdenay** [comment]
TODO for DADA2 for me

**Comment by gregdenay** [comment]
implemented for DADA2 in [0db284e](https://github.com/bio-raum/FooDMe2/commit/0db284eb47b4c66ded8d70939c5e7d16aafb2d7f)
